version: '3.3'
services:
  freqtrade-backtest:
    image: freqtradeorg/freqtrade:develop
    command: -s ../config/BackTestStrategy -c ../config/config-backtest.json backtesting --export trades --export-filename=backtest_output.json
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/freqtrade/config/backtest-config.json:/freqtrade/config.json
      - ~/freqtrade/tradesv3.backtest.sqlite:/freqtrade/tradesv3.sqlite
      - ~/freqtrade/backtest_output.json:/freqtrade/backtest_output.json
